{
  inputs,
  lib,
  ...
} @ top: {
  imports = [inputs.flake-file.flakeModules.default];

  flake-file = {
    description = "Cached nix packages for thou";

    do-not-edit =
      # nix
      ''
        # DO NOT EDIT!
        # Auto-generated by nix run .#write-flake from flake-file
        # The outputs are in ./modules/outputs.nix
        # The static part is defined at ./modules/flake-file.nix
      '';

    formatter = pkgs: pkgs.alejandra;

    inputs = {
      flake-file.url = "github:denful/flake-file";

      flake-parts = {
        url = "github:hercules-ci/flake-parts";
        inputs.nixpkgs-lib.follows = "nixpkgs";
      };

      helix-steel = {
        url = "github:mattwparas/helix/steel-event-system";
        inputs = {
          nixpkgs.follows = "nixpkgs";
          rust-overlay.follows = "rust-overlay";
        };
      };

      import-tree.url = "github:vic/import-tree";

      nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

      rust-overlay = {
        url = "github:oxalica/rust-overlay";
        inputs.nixpkgs.follows = "nixpkgs";
      };

      treefmt-nix = {
        url = "github:numtide/treefmt-nix";
        inputs = {
          nixpkgs.follows = "nixpkgs";
        };
      };
    };

    nixConfig = {
      extra-substituters = ["https://thou-vow.cachix.org"];
      extra-trusted-public-keys = ["thou-vow.cachix.org-1:n6zUvWYOI7kh0jgd+ghWhxeMd9tVdYF2KdOvufJ/Qy4="];
    };

    outputs =
      # nix
      ''inputs: inputs.flake-parts.lib.mkFlake {inherit inputs;} (inputs.import-tree ./modules)'';
  };
}
