[apple-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji-Linux.ttf"

[brave-latest-aarch64-linux]
src.github = "brave/brave-browser"
src.prefix = "v"
fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_arm64.deb"

[brave-latest-x64-linux]
# src.github = "brave/brave-browser"
# src.prefix = "v"
src.manual = "1.90.124"
fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_amd64.deb"

[discord-rpc-lsp]
src.github = "zerootoad/discord-rpc-lsp"
fetch.github = "zerootoad/discord-rpc-lsp"

[dwproton-x64-linux]
src.webpage = "https://dawn.wine/dawn-winery/dwproton/releases"
src.regex = 'dwproton-([\d.]+-\d+)-x86_64\.tar\.xz'
fetch.zip = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-$ver/dwproton-$ver-x86_64.tar.xz"

[faugus-launcher]
src.github = "Faugus/faugus-launcher"
fetch.github = "Faugus/faugus-launcher"

[graalvm-oracle-21-aarch64-linux]
src.manual = "21.0.11"
fetch.url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-$ver_linux-aarch64_bin.tar.gz"

[graalvm-oracle-21-x64-linux]
src.manual = "21.0.11"
fetch.url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-$ver_linux-x64_bin.tar.gz"

[graalvm-oracle-25-aarch64-linux]
src.manual = "25.0.3"
fetch.url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-$ver_linux-aarch64_bin.tar.gz"

[graalvm-oracle-25-x64-linux]
src.manual = "25.0.3"
fetch.url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-$ver_linux-x64_bin.tar.gz"

[proton-cachyos-x64-linux]
src.github = "CachyOS/proton-cachyos"
src.prefix = "cachyos-"
fetch.zip = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-$ver/proton-cachyos-$ver-x86_64.tar.xz"

[proton-cachyos-x64-linux-v3]
src.github = "CachyOS/proton-cachyos"
src.prefix = "cachyos-"
fetch.zip = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-$ver/proton-cachyos-$ver-x86_64_v3.tar.xz"

[proton-ge-x64-linux]
src.github = "GloriousEggroll/proton-ge-custom"
src.prefix = "GE-Proton"
fetch.zip = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton$ver/GE-Proton$ver.tar.gz"
