[apple-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji-Linux.ttf"

[brave-aarch64-linux]
src.github = "brave/brave-browser"
src.prefix = "v"
fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_arm64.deb"

[brave-x64-linux]
src.github = "brave/brave-browser"
src.prefix = "v"
fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_amd64.deb"

[discord-rpc-lsp]
src.github = "zerootoad/discord-rpc-lsp"
fetch.github = "zerootoad/discord-rpc-lsp"

[graalvm-oracle-21-aarch64-linux]
src.manual = "21.0.11"
fetch.url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-$ver_linux-aarch64_bin.tar.gz"

[graalvm-oracle-21-x64-linux]
src.manual = "21.0.11"
fetch.url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-$ver_linux-x64_bin.tar.gz"

[graalvm-oracle-25-aarch64-linux]
src.manual = "25.0.3"
fetch.url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-$ver_linux-aarch64_bin.tar.gz"

[graalvm-oracle-25-x64-linux]
src.manual = "25.0.3"
fetch.url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-$ver_linux-x64_bin.tar.gz"


