[inputs.nixpkgs]
url = "https://channels.nixos.org/nixos-unstable/nixexprs.tar.zst"
group = "maintenance"

[inputs.tack]
url = "github:manic-systems/tack"
group = "maintenance"

[inputs.treefmt-nix]
url = "github:numtide/treefmt-nix"
type = "fetch"
group = "maintenance"


[inputs.discord-rpc-lsp]
url = "github:zerootoad/discord-rpc-lsp"
type = "fetch"
tag = "{version}"
group = "packages"

[inputs.brave-aarch64-linux]
url = "https://github.com/brave/brave-browser/releases/download/{tag}/brave-browser_{version}_arm64.deb"
type = "fixed"
unpack = "file"
tag = "v{version}"
tags_from = "https://brave.com/latest"
group = "packages"

[inputs.brave-x86-64-linux]
url = "https://github.com/brave/brave-browser/releases/download/{tag}/brave-browser_{version}_amd64.deb"
type = "fixed"
unpack = "file"
tag = "v{version}"
tags_from = "https://brave.com/latest"
group = "packages"

[inputs.dwproton-x86-64-linux]
url = "https://dawn.wine/dawn-winery/dwproton/releases/download/{tag}/{tag}-x86_64.tar.xz"
type = "fixed"
unpack = "tarball"
tag = "dwproton-{version}"
tags_from = "https://dawn.wine/dawn-winery/dwproton/releases"
group = "packages"

[inputs.faugus-launcher]
url = "github:Faugus/faugus-launcher"
type = "fetch"
tag = "{version}"
group = "packages"

[inputs.graalvm-oracle-21-aarch64-linux]
url = "https://gds.oracle.com/download/graal/21/archive/graalvm-jdk-{version}_linux-aarch64_bin.tar.gz"
type = "fixed"
unpack = "file"
tag = "Oracle GraalVM for JDK {version}"
tags_from = "https://docs.oracle.com/en/graalvm/jdk/21/docs/release-notes"
group = "packages"

[inputs.graalvm-oracle-21-x86-64-linux]
url = "https://gds.oracle.com/download/graal/21/archive/graalvm-jdk-{version}_linux-x64_bin.tar.gz"
type = "fixed"
unpack = "file"
tag = "Oracle GraalVM for JDK {version}"
tags_from = "https://docs.oracle.com/en/graalvm/jdk/21/docs/release-notes"
group = "packages"

[inputs.graalvm-oracle-25-aarch64-linux]
url = "https://gds.oracle.com/download/graal/25/archive/graalvm-jdk-{version}_linux-aarch64_bin.tar.gz"
type = "fixed"
unpack = "file"
tag = "Oracle GraalVM {version}"
tags_from = "https://docs.oracle.com/en/graalvm/jdk/25/docs/release-notes"
group = "packages"

[inputs.graalvm-oracle-25-x86-64-linux]
url = "https://gds.oracle.com/download/graal/25/archive/graalvm-jdk-{version}_linux-x64_bin.tar.gz"
type = "fixed"
unpack = "file"
tag = "Oracle GraalVM {version}"
tags_from = "https://docs.oracle.com/en/graalvm/jdk/25/docs/release-notes"
group = "packages"

[inputs.llama-prism]
url = "github:PrismML-Eng/llama.cpp"
type = "fetch"
tag = "prism-b{version}-*"
group = "packages"

[inputs.prismlauncher-cracked]
url = "github:Diegiwg/PrismLauncher-Cracked"
type = "fetch"
tag = "{version}"
group = "packages"

[inputs.proton-cachyos-x86-64-linux]
url = "https://github.com/CachyOS/proton-cachyos/releases/download/{tag}/proton-{tag}-x86_64.tar.xz"
type = "fixed"
unpack = "tarball"
tag = "cachyos-{version}-slr"
group = "packages"

[inputs.proton-cachyos-x86-64-v3-linux]
url = "https://github.com/CachyOS/proton-cachyos/releases/download/{tag}/proton-{tag}-x86_64_v3.tar.xz"
type = "fixed"
unpack = "tarball"
tag = "cachyos-{version}-slr"
group = "packages"

[inputs.proton-ge-x86-64-linux]
url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/{tag}/{tag}-x86_64.tar.gz"
type = "fixed"
unpack = "tarball"
tag = "GE-Proton{version}"
group = "packages"

[inputs.proton-wineland-x86-64-linux]
url = "https://github.com/nanomatters/proton-cachyos/releases/download/{tag}/proton-{tag}-x86_64.tar.xz"
type = "fixed"
unpack = "tarball"
tag = "wineland-{version}"
group = "packages"

[inputs.proton-wineland-x86-64-v3-linux]
url = "https://github.com/nanomatters/proton-cachyos/releases/download/{tag}/proton-{tag}-x86_64_v3.tar.xz"
type = "fixed"
unpack = "tarball"
tag = "wineland-{version}"
group = "packages"
