# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260613-f1fc560b";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260613-f1fc560b/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-uMjtl/ZCuJuko2o+CWYZ8IBdBswlrhEW5pU7mBQq4gw=";
    };
  };
  brave-aarch64-linux = {
    pname = "brave-aarch64-linux";
    version = "1.92.141";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.92.141/brave-browser_1.92.141_arm64.deb";
      sha256 = "sha256-FVzXaVpyfX+GIVofy3NfpE8rOH+9LjQpdEoEWQV0DqI=";
    };
  };
  brave-x64-linux = {
    pname = "brave-x64-linux";
    version = "1.92.141";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.92.141/brave-browser_1.92.141_amd64.deb";
      sha256 = "sha256-A87vCTtcyuNMPLaLYDjgyIm85zwAXNc3Z4ImtC9Kjek=";
    };
  };
  discord-rpc-lsp = {
    pname = "discord-rpc-lsp";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "zerootoad";
      repo = "discord-rpc-lsp";
      rev = "1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-1Zw+F/EfYjHHU0AYlAHT7g1sbuJrHRtGp9E1u9EPW8E=";
    };
  };
  dwproton-x64-linux = {
    pname = "dwproton-x64-linux";
    version = "11.0-7";
    src = fetchzip {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-7/dwproton-11.0-7-x86_64.tar.xz";
      sha256 = "sha256-M8wcC7pKFs0Qena5NN9ylq2TykRfPK7JiHnzP6DkZv0=";
    };
  };
  faugus-launcher = {
    pname = "faugus-launcher";
    version = "1.22.8";
    src = fetchFromGitHub {
      owner = "Faugus";
      repo = "faugus-launcher";
      rev = "1.22.8";
      fetchSubmodules = false;
      sha256 = "sha256-2FsuD40u5O7VwbziTqhsfVyceyfmSRvdmsizfBy/Xys=";
    };
  };
  graalvm-oracle-21-aarch64-linux = {
    pname = "graalvm-oracle-21-aarch64-linux";
    version = "21.0.11";
    src = fetchurl {
      url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.11_linux-aarch64_bin.tar.gz";
      sha256 = "sha256-hvxfORvjG53b5HNwtwUwPBpkm9eJFf/sz4x4pDDqy0w=";
    };
  };
  graalvm-oracle-21-x64-linux = {
    pname = "graalvm-oracle-21-x64-linux";
    version = "21.0.11";
    src = fetchurl {
      url = "https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.11_linux-x64_bin.tar.gz";
      sha256 = "sha256-Iw5TdqnDINwy9dnqSCEN4ztfzhbHWdRufPoiY8FzIRg=";
    };
  };
  graalvm-oracle-25-aarch64-linux = {
    pname = "graalvm-oracle-25-aarch64-linux";
    version = "25.0.3";
    src = fetchurl {
      url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-25.0.3_linux-aarch64_bin.tar.gz";
      sha256 = "sha256-LG5e9jCExfOcZ8v1wz0jyFLfhI0QzVDXbmZ//5yc8rw=";
    };
  };
  graalvm-oracle-25-x64-linux = {
    pname = "graalvm-oracle-25-x64-linux";
    version = "25.0.3";
    src = fetchurl {
      url = "https://download.oracle.com/graalvm/25/archive/graalvm-jdk-25.0.3_linux-x64_bin.tar.gz";
      sha256 = "sha256-G1KWYTw9ElIdWU4cmTAt+I2OHwfXSreYPb9XIAC5LHw=";
    };
  };
  helix-steel = {
    pname = "helix-steel";
    version = "0522d519fd5227f77ecef387a87e51b732907562";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "helix";
      rev = "0522d519fd5227f77ecef387a87e51b732907562";
      fetchSubmodules = false;
      sha256 = "sha256-bGfByNnjuzENdvTW97s4UhwglYY7ydBk54gOZmnaM4Q=";
    };
    date = "2026-06-21";
  };
  noctalia = {
    pname = "noctalia";
    version = "v5.0.0-beta.3";
    src = fetchFromGitHub {
      owner = "noctalia-dev";
      repo = "noctalia";
      rev = "v5.0.0-beta.3";
      fetchSubmodules = false;
      sha256 = "sha256-8iAeWIjw2OMfsBCtaGcmR14lgBX0MOoaBaSyBwieBsA=";
    };
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
    src = fetchFromGitHub {
      owner = "thou-vow";
      repo = "nvfetcher";
      rev = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
      fetchSubmodules = false;
      sha256 = "sha256-9PQK8mnzZoMUHPsY7PcFP0WoqhlHZzxjpTPdB6H+TOg=";
    };
    date = "2026-06-08";
  };
  prismlauncher-cracked = {
    pname = "prismlauncher-cracked";
    version = "11.0.3";
    src = fetchFromGitHub {
      owner = "Diegiwg";
      repo = "PrismLauncher-Cracked";
      rev = "11.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-pFIDOP03I76r14bXoKL7tEEaLlGFJ10MqMgGR4D/mvE=";
    };
  };
  proton-cachyos-x64-linux = {
    pname = "proton-cachyos-x64-linux";
    version = "11.0-20260702-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260702-slr/proton-cachyos-11.0-20260702-slr-x86_64.tar.xz";
      sha256 = "sha256-ZyyhEf6NcW7MzswWAlMdE4Ok8KnBOmB81yvu8ZwVxl4=";
    };
  };
  proton-cachyos-x64-linux-v3 = {
    pname = "proton-cachyos-x64-linux-v3";
    version = "11.0-20260702-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260702-slr/proton-cachyos-11.0-20260702-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-pbx/WDgpa55WDr1exD4rrNWsRoVkqHIUjzX1PJObxG8=";
    };
  };
  proton-ge-x64-linux = {
    pname = "proton-ge-x64-linux";
    version = "11-1";
    src = fetchzip {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-1/GE-Proton11-1.tar.gz";
      sha256 = "sha256-I7SSvzQQ/NqdvwjpJ9IFFtAaTS+rgHUyXx0us1vIOnw=";
    };
  };
  treefmt-nix = {
    pname = "treefmt-nix";
    version = "df3c0640565d04a0261253cdd89fce78ec50168a";
    src = fetchFromGitHub {
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "df3c0640565d04a0261253cdd89fce78ec50168a";
      fetchSubmodules = false;
      sha256 = "sha256-47cxbcZODibHv3rELFQ9vZly0vUNkND/atn/U7HLeb0=";
    };
    date = "2026-07-18";
  };
}
