# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchzip,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260722-484daf4e";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260722-484daf4e/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-43x69iZaxKCvbVe8ZehhCad22ZZug0MzRVf2PaSCUW8=";
    };
  };
  brave-aarch64-linux = {
    pname = "brave-aarch64-linux";
    version = "1.95.104";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.95.104/brave-browser_1.95.104_arm64.deb";
      sha256 = "sha256-JR7oP6OD22EGrmFA3wl1aJsibRXOuWzbQUfLkM18Jbo=";
    };
  };
  brave-x64-linux = {
    pname = "brave-x64-linux";
    version = "1.95.104";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.95.104/brave-browser_1.95.104_amd64.deb";
      sha256 = "sha256-4J48Pp/IT3XmUEigvoMMfEkHdEpAK1eQUw0iBrJ2Qm4=";
    };
  };
  discord-rpc-lsp = {
    pname = "discord-rpc-lsp";
    version = "1.0.1";
    src = fetchFromGitHub {
      owner = "zerootoad";
      repo = "discord-rpc-lsp";
      rev = "1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-1Zw+F/EfYjHHU0AYlAHT7g1sbuJrHRtGp9E1u9EPW8E=";
    };
  };
  dwproton-x64-linux = {
    pname = "dwproton-x64-linux";
    version = "11.0-13";
    src = fetchzip {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-13/dwproton-11.0-13-x86_64.tar.xz";
      sha256 = "sha256-INbvpKk01gMyt72Z2jlJvov5k4LZztpFuiYgVkGBc1I=";
    };
  };
  faugus-launcher = {
    pname = "faugus-launcher";
    version = "2.4.0";
    src = fetchFromGitHub {
      owner = "Faugus";
      repo = "faugus-launcher";
      rev = "2.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-8+AxxpjJYE6AzTwVIVimK9shUu0BIkUlMINxaqq4d5k=";
    };
  };
  graalvm-oracle-21-aarch64-linux = {
    pname = "graalvm-oracle-21-aarch64-linux";
    version = "21.0.12.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/21/archive/graalvm-jdk-21.0.12.1_linux-aarch64_bin.tar.gz";
      sha256 = "sha256-JaNr5xftugNs4VQCCTBpQlE9kRNB29DZp/+X0QVbBCw=";
    };
  };
  graalvm-oracle-21-x64-linux = {
    pname = "graalvm-oracle-21-x64-linux";
    version = "21.0.12.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/21/archive/graalvm-jdk-21.0.12.1_linux-x64_bin.tar.gz";
      sha256 = "sha256-cHSvqVUVqNhxNHIALzMKyYOaBv4W7ltdoSi0MDdsL9k=";
    };
  };
  graalvm-oracle-25-aarch64-linux = {
    pname = "graalvm-oracle-25-aarch64-linux";
    version = "25.0.4.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/25/archive/graalvm-jdk-25.0.4.1_linux-aarch64_bin.tar.gz";
      sha256 = "sha256-g49rqr2rdUY8byHwcfLMYpUBlIIJzYFxjpVr11h4SiQ=";
    };
  };
  graalvm-oracle-25-x64-linux = {
    pname = "graalvm-oracle-25-x64-linux";
    version = "25.0.4.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/25/archive/graalvm-jdk-25.0.4.1_linux-x64_bin.tar.gz";
      sha256 = "sha256-CVyWY8OmdBtV7POuaZKU3CYKYrUjrPbevIUL3LIjBXw=";
    };
  };
  graalvm-oracle-25i-aarch64-linux = {
    pname = "graalvm-oracle-25i-aarch64-linux";
    version = "25i4-25.0.4.1.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/25i4/archive/graalvm-jdk-25i4-25.0.4.1.1_linux-aarch64_bin.tar.gz";
      sha256 = "sha256-eA1XhNPbm7z/d3dcTQJuSg4hoEG6nbp8WRNZSepSNKQ=";
    };
  };
  graalvm-oracle-25i-x64-linux = {
    pname = "graalvm-oracle-25i-x64-linux";
    version = "25i4-25.0.4.1.1";
    src = fetchurl {
      url = "https://gds.oracle.com/download/graal/25i4/archive/graalvm-jdk-25i4-25.0.4.1.1_linux-x64_bin.tar.gz";
      sha256 = "sha256-T8xjLPxo6Y9J+TFvijWIuv5PUonxIBBOLSkKdc8z4o4=";
    };
  };
  helix-steel = {
    pname = "helix-steel";
    version = "7915ec19939d8ae3ab4cfff278eaf23ae3784351";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "helix";
      rev = "7915ec19939d8ae3ab4cfff278eaf23ae3784351";
      fetchSubmodules = false;
      sha256 = "sha256-cfZ9EL0rRfoB7KnZRgRmk36YJhjfutqDjzew1lJYwEg=";
    };
    date = "2026-09-21";
  };
  nvfetcher = {
    pname = "nvfetcher";
    version = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
    src = fetchFromGitHub {
      owner = "thou-vow";
      repo = "nvfetcher";
      rev = "b909de1eddb7c21b014abe88e37e5bd71f30f638";
      fetchSubmodules = false;
      sha256 = "sha256-9PQK8mnzZoMUHPsY7PcFP0WoqhlHZzxjpTPdB6H+TOg=";
    };
    date = "2026-06-08";
  };
  prismlauncher-cracked = {
    pname = "prismlauncher-cracked";
    version = "11.0.3";
    src = fetchFromGitHub {
      owner = "Diegiwg";
      repo = "PrismLauncher-Cracked";
      rev = "11.0.3";
      fetchSubmodules = false;
      sha256 = "sha256-pFIDOP03I76r14bXoKL7tEEaLlGFJ10MqMgGR4D/mvE=";
    };
  };
  proton-cachyos-x64-linux = {
    pname = "proton-cachyos-x64-linux";
    version = "11.0-20260703-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260703-slr/proton-cachyos-11.0-20260703-slr-x86_64.tar.xz";
      sha256 = "sha256-jOcPeEkBBPPNqyjXBoHm1Nk8AexPiLhx5+385NjUPT0=";
    };
  };
  proton-cachyos-x64-linux-v3 = {
    pname = "proton-cachyos-x64-linux-v3";
    version = "11.0-20260703-slr";
    src = fetchzip {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260703-slr/proton-cachyos-11.0-20260703-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-8Y7orUvnFOG0zSqCrMyvmclmy3JInj7d8A2h0Y7RwhE=";
    };
  };
  proton-ge-x64-linux = {
    pname = "proton-ge-x64-linux";
    version = "11-7";
    src = fetchzip {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton11-7/GE-Proton11-7-x86_64.tar.gz";
      sha256 = "sha256-ftW0vE45v2JsbaYqo/So0ZFfvdtakHX0XEXEE4TdxLk=";
    };
  };
  treefmt-nix = {
    pname = "treefmt-nix";
    version = "27b3b12a8e6375f28ebe122f07d230ca5459bbfa";
    src = fetchFromGitHub {
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "27b3b12a8e6375f28ebe122f07d230ca5459bbfa";
      fetchSubmodules = false;
      sha256 = "sha256-WSFCsDSE5ffgD2MqzkM2CYjeFiKhRF/dJUN8uedb6YE=";
    };
    date = "2026-08-16";
  };
}
