name: Build cache after a commit
on:
  push:
  workflow_dispatch:
concurrency:
  group: bump
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build cache
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --cachix-cache thou-vow --no-nom --skip-cache --systems "aarch64-linux x86_64-linux"
