name: Build cache (after a commit) without updating
on:
  push:
  workflow_dispatch:
concurrency:
  group: cache
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
          - runner: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reclaim space!
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            build-dir = /nix/build

      - name: Build cache
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run .#determinate-nix-fast-build -- --file ./ci-cache.nix \
            --cachix-cache thou-vow --no-nom --skip-cached
