name: Build cache after a commit
on:
  push:
  workflow_dispatch:
concurrency:
  group: bump
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = flakes nix-command pipe-operators
          install_options: --no-daemon
      - env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run --inputs-from . nixpkgs#nix-fast-build -- \
            --cachix-cache thou-vow --no-nom --skip-cached \
            --no-link --flake .#checks.x86_64-linux
