name: Build cache after a commit
on:
  push:
  workflow_dispatch:
concurrency:
  group: bump
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: canidae-solutions/lix-quick-install-action@v3
        with:
          lix_conf: |
            extra-experimental-features = pipe-operator
      - env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run --inputs-from . nixpkgs#lixPackageSets.latest.nix-fast-build -- \
            --cachix-cache thou-vow --no-nom --skip-cache
