name: Build cache after a commit
on:
  push:
  workflow_dispatch:
concurrency:
  group: bump
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3
      - name: Build cache
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run nixpkgs#lixPackageSets.latest.nix-fast-build -- \
            --cachix-cache thou-vow --no-nom --skip-cache
