name: Periodically bump flake.lock (and build cache)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
permissions:
  contents: write
concurrency:
  group: bump
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3
      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Update flake.lock
        id: update
        run: |
          nix --accept-flake-config flake update
          if git diff --quiet -- flake.lock; then
            echo "flake.lock unchanged"
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "updated=true" >> $GITHUB_OUTPUT
          fi
      - name: Build cache
        if: steps.update.outputs.updated == 'true'
        run: |
          cachix watch-exec -m xz -l 5 thou-vow -- \
            nix --accept-flake-config \
            build -L --impure --expr \
            'let
              packages = (builtins.getFlake (builtins.toString ./.)).legacyPackages;
            in
              (with packages."x86_64-linux"; [
                helix-steel
              ])
              ++ (with packages."x86_64-linux".attunedPackages; [
                helix-steel
                linux-llvm
                niri-unstable
                nixd
                rust-analyzer-unwrapped
                xwayland-satellite-unstable
              ])'
      - name: Commit and push flake.lock
        if: steps.update.outputs.updated == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "ci: bump packages to $(date +%Y-%m-%dT%H:%MZ)"
          git push
