name: Periodically bump flake.lock (and build cache)
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *
permissions:
  contents: write
concurrency:
  group: bump
  cancel-in-progress: true
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        run: |
          nix --accept-flake-config flake update
          if git diff --quiet -- flake.lock; then
            echo "flake.lock unchanged"
            exit 0
          fi
      - name: Build cache
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --cachix-cache thou-vow --no-nom --skip-cache --systems "aarch64-linux x86_64-linux"
      - name: Commit and push flake.lock
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          git commit -m "ci: bump packages to $(date %Y-%m-%dT%H:%MZ)"
          git push
