name: Build cache for a single package
on:
  workflow_dispatch:
    inputs:
      package:
        description: Derivation in legacyPackages (e.g. "x86_64-linux".attunedPackages.helix-steel)
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Lix
        uses: canidae-solutions/lix-quick-install-action@v3
      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: thou-vow
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build cache
        env:
          PACKAGE: ${{ github.event.inputs.package }}
        run: |
          cachix watch-exec -m xz -l 5 thou-vow -- \
            nix --accept-flake-config \
            build -L --impure --expr \
            "(builtins.getFlake (builtins.toString ./.)).legacyPackages.$PACKAGE"
